### ISSUE TITLE
brace example traceback error

### ISSUE THREAD

**Issue by Extraweich** [FAST-LB/pyGCodeDecode#1]
The second example does not run, using the current version "0.2.0" through pypi, giving the following error: 

> Only a machine name was specified but no full setup. Trying to create a setup from pyGCD's default values...
Traceback (most recent call last):
  File "D:\Code\Python\pyGCodeDecode\examples\brace\brace.py", line 11, in <module>
    brace_simulation = simulation(gcode_path=script_dir / "data" / "brace.gcode", machine_name="anisoprint_a4")
  File "C:\Anaconda3\envs\pyGCodeDecode\lib\site-packages\pyGCodeDecode\gcode_interpreter.py", line 215, in __init__
    default_presets_file = importlib.resources.files("pyGCodeDecode").joinpath(
AttributeError: module 'importlib' has no attribute 'resources'

According to @FelixFroelich, changing `import importlib` -> `import importlib.resources` in gcode_interpreter.py seems to fix this issue.

**Comment by lukashof** [comment]
Thank you for making us aware! I'll fix it asap!
